name: Bot Anime News

on:
  schedule:
    - cron: '0 9,15,21 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4
      
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Instalar dependencias
        run: pip install -r requirements.txt
      
      - name: Crear credentials.json
        run: echo '${{ secrets.CREDENTIALS_JSON }}' > credentials.json
      - name: Crear token.json
      
        run: echo '${{ secrets.TOKEN_JSON }}' > token.json
        
      - name: Ejecutar bot
        env:
          BLOGGER_BLOG_ID: ${{ secrets.BLOGGER_BLOG_ID }}
        run: |
          python bot_anime.py
